# coding: utf-8

"""
    myCalibration OpenAPI 3 Specification

    myCalibration API  # noqa: E501

    OpenAPI spec version: 1.22.178.1
    Contact: engineering@keller-druck.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.physical_quantity_range import PhysicalQuantityRange  # noqa: E501
from swagger_client.rest import ApiException


class TestPhysicalQuantityRange(unittest.TestCase):
    """PhysicalQuantityRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhysicalQuantityRange(self):
        """Test PhysicalQuantityRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.physical_quantity_range.PhysicalQuantityRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
