# coding: utf-8

"""
    myCalibration OpenAPI 3 Specification

    myCalibration API  # noqa: E501

    OpenAPI spec version: 1.22.178.1
    Contact: engineering@keller-pressure.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.calibration_data_api import CalibrationDataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCalibrationDataApi(unittest.TestCase):
    """CalibrationDataApi unit test stubs"""

    def setUp(self):
        self.api = CalibrationDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_calibration_data_get_calibration_data(self):
        """Test case for calibration_data_get_calibration_data

        Gathers all filtered data in one JSON response  # noqa: E501
        """
        pass

    def test_calibration_data_get_calibration_data_as_file(self):
        """Test case for calibration_data_get_calibration_data_as_file

        Locates the filtered (optionalSearchParameter) data, bundles them and creates a download link  # noqa: E501
        """
        pass

    def test_calibration_data_get_calibration_data_headers(self):
        """Test case for calibration_data_get_calibration_data_headers

        Get a list with all meta-information.  # noqa: E501
        """
        pass

    def test_calibration_data_sync_calibration_data(self):
        """Test case for calibration_data_sync_calibration_data

        Only used for maintenance reasons. Do not use!  # noqa: E501
        """
        pass

    def test_me_get_me_details(self):
        """Test case for me_get_me_details

        """
        pass

    def test_profile_get_profile(self):
        """Test case for profile_get_profile

        """
        pass

    def test_profile_update_profile(self):
        """Test case for profile_update_profile

        """
        pass

    def test_sub_customer_update_sub_customers(self):
        """Test case for sub_customer_update_sub_customers

        """
        pass


if __name__ == '__main__':
    unittest.main()
