# coding: utf-8

"""
    myCalibration OpenAPI 3 Specification

    myCalibration API  # noqa: E501

    OpenAPI spec version: 1.22.178.1
    Contact: engineering@keller-druck.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompensationMethods(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mathematical_models': 'dict(str, MathematicalModel)',
        'compensation_circuit': 'CompensationCircuit'
    }

    attribute_map = {
        'mathematical_models': 'MathematicalModels',
        'compensation_circuit': 'CompensationCircuit'
    }

    def __init__(self, mathematical_models=None, compensation_circuit=None):  # noqa: E501
        """CompensationMethods - a model defined in Swagger"""  # noqa: E501
        self._mathematical_models = None
        self._compensation_circuit = None
        self.discriminator = None
        if mathematical_models is not None:
            self.mathematical_models = mathematical_models
        if compensation_circuit is not None:
            self.compensation_circuit = compensation_circuit

    @property
    def mathematical_models(self):
        """Gets the mathematical_models of this CompensationMethods.  # noqa: E501


        :return: The mathematical_models of this CompensationMethods.  # noqa: E501
        :rtype: dict(str, MathematicalModel)
        """
        return self._mathematical_models

    @mathematical_models.setter
    def mathematical_models(self, mathematical_models):
        """Sets the mathematical_models of this CompensationMethods.


        :param mathematical_models: The mathematical_models of this CompensationMethods.  # noqa: E501
        :type: dict(str, MathematicalModel)
        """

        self._mathematical_models = mathematical_models

    @property
    def compensation_circuit(self):
        """Gets the compensation_circuit of this CompensationMethods.  # noqa: E501


        :return: The compensation_circuit of this CompensationMethods.  # noqa: E501
        :rtype: CompensationCircuit
        """
        return self._compensation_circuit

    @compensation_circuit.setter
    def compensation_circuit(self, compensation_circuit):
        """Sets the compensation_circuit of this CompensationMethods.


        :param compensation_circuit: The compensation_circuit of this CompensationMethods.  # noqa: E501
        :type: CompensationCircuit
        """

        self._compensation_circuit = compensation_circuit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompensationMethods, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompensationMethods):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
