# coding: utf-8

"""
    myCalibration OpenAPI 3 Specification

    myCalibration API  # noqa: E501

    OpenAPI spec version: 1.22.178.1
    Contact: engineering@keller-druck.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompensationCircuitOutputValue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'measured_value': 'PhysicalQuantity',
        'nominal_value': 'PhysicalQuantity'
    }

    attribute_map = {
        'measured_value': 'MeasuredValue',
        'nominal_value': 'NominalValue'
    }

    def __init__(self, measured_value=None, nominal_value=None):  # noqa: E501
        """CompensationCircuitOutputValue - a model defined in Swagger"""  # noqa: E501
        self._measured_value = None
        self._nominal_value = None
        self.discriminator = None
        if measured_value is not None:
            self.measured_value = measured_value
        if nominal_value is not None:
            self.nominal_value = nominal_value

    @property
    def measured_value(self):
        """Gets the measured_value of this CompensationCircuitOutputValue.  # noqa: E501


        :return: The measured_value of this CompensationCircuitOutputValue.  # noqa: E501
        :rtype: PhysicalQuantity
        """
        return self._measured_value

    @measured_value.setter
    def measured_value(self, measured_value):
        """Sets the measured_value of this CompensationCircuitOutputValue.


        :param measured_value: The measured_value of this CompensationCircuitOutputValue.  # noqa: E501
        :type: PhysicalQuantity
        """

        self._measured_value = measured_value

    @property
    def nominal_value(self):
        """Gets the nominal_value of this CompensationCircuitOutputValue.  # noqa: E501


        :return: The nominal_value of this CompensationCircuitOutputValue.  # noqa: E501
        :rtype: PhysicalQuantity
        """
        return self._nominal_value

    @nominal_value.setter
    def nominal_value(self, nominal_value):
        """Sets the nominal_value of this CompensationCircuitOutputValue.


        :param nominal_value: The nominal_value of this CompensationCircuitOutputValue.  # noqa: E501
        :type: PhysicalQuantity
        """

        self._nominal_value = nominal_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompensationCircuitOutputValue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompensationCircuitOutputValue):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
