# coding: utf-8

"""
    myCalibration OpenAPI 3 Specification

    myCalibration API  # noqa: E501

    OpenAPI spec version: 1.22.178.1
    Contact: engineering@keller-pressure.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MefistoViewModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'customer_name': 'str',
        'customer_number': 'int',
        'sub_customer_number': 'int',
        'remarks': 'str',
        'serial_number': 'str',
        'product_number': 'str',
        'product_type': 'str',
        'pressure_type': 'str',
        'product_series': 'str',
        'compensated_temperature_range_min': 'float',
        'compensated_temperature_range_max': 'float',
        'compensated_temperature_range_unit': 'str',
        'compensated_pressure_range_min': 'float',
        'compensated_pressure_range_max': 'float',
        'compensated_pressure_range_unit': 'str',
        'electric_supply_min': 'float',
        'electric_supply_max': 'float',
        'electric_supply_magnitude': 'float',
        'electric_supply_unit': 'str',
        'order_number': 'int',
        'order_position': 'int',
        'order_target_dispatch_date': 'datetime',
        'customer_order_number': 'str',
        'customer_reference_number': 'str',
        'customer_product_type': 'str'
    }

    attribute_map = {
        'id': 'Id',
        'customer_name': 'CustomerName',
        'customer_number': 'CustomerNumber',
        'sub_customer_number': 'SubCustomerNumber',
        'remarks': 'Remarks',
        'serial_number': 'SerialNumber',
        'product_number': 'ProductNumber',
        'product_type': 'ProductType',
        'pressure_type': 'PressureType',
        'product_series': 'ProductSeries',
        'compensated_temperature_range_min': 'CompensatedTemperatureRangeMin',
        'compensated_temperature_range_max': 'CompensatedTemperatureRangeMax',
        'compensated_temperature_range_unit': 'CompensatedTemperatureRangeUnit',
        'compensated_pressure_range_min': 'CompensatedPressureRangeMin',
        'compensated_pressure_range_max': 'CompensatedPressureRangeMax',
        'compensated_pressure_range_unit': 'CompensatedPressureRangeUnit',
        'electric_supply_min': 'ElectricSupplyMin',
        'electric_supply_max': 'ElectricSupplyMax',
        'electric_supply_magnitude': 'ElectricSupplyMagnitude',
        'electric_supply_unit': 'ElectricSupplyUnit',
        'order_number': 'OrderNumber',
        'order_position': 'OrderPosition',
        'order_target_dispatch_date': 'OrderTargetDispatchDate',
        'customer_order_number': 'CustomerOrderNumber',
        'customer_reference_number': 'CustomerReferenceNumber',
        'customer_product_type': 'CustomerProductType'
    }

    def __init__(self, id=None, customer_name=None, customer_number=None, sub_customer_number=None, remarks=None, serial_number=None, product_number=None, product_type=None, pressure_type=None, product_series=None, compensated_temperature_range_min=None, compensated_temperature_range_max=None, compensated_temperature_range_unit=None, compensated_pressure_range_min=None, compensated_pressure_range_max=None, compensated_pressure_range_unit=None, electric_supply_min=None, electric_supply_max=None, electric_supply_magnitude=None, electric_supply_unit=None, order_number=None, order_position=None, order_target_dispatch_date=None, customer_order_number=None, customer_reference_number=None, customer_product_type=None):  # noqa: E501
        """MefistoViewModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._customer_name = None
        self._customer_number = None
        self._sub_customer_number = None
        self._remarks = None
        self._serial_number = None
        self._product_number = None
        self._product_type = None
        self._pressure_type = None
        self._product_series = None
        self._compensated_temperature_range_min = None
        self._compensated_temperature_range_max = None
        self._compensated_temperature_range_unit = None
        self._compensated_pressure_range_min = None
        self._compensated_pressure_range_max = None
        self._compensated_pressure_range_unit = None
        self._electric_supply_min = None
        self._electric_supply_max = None
        self._electric_supply_magnitude = None
        self._electric_supply_unit = None
        self._order_number = None
        self._order_position = None
        self._order_target_dispatch_date = None
        self._customer_order_number = None
        self._customer_reference_number = None
        self._customer_product_type = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if customer_name is not None:
            self.customer_name = customer_name
        if customer_number is not None:
            self.customer_number = customer_number
        if sub_customer_number is not None:
            self.sub_customer_number = sub_customer_number
        if remarks is not None:
            self.remarks = remarks
        if serial_number is not None:
            self.serial_number = serial_number
        if product_number is not None:
            self.product_number = product_number
        if product_type is not None:
            self.product_type = product_type
        if pressure_type is not None:
            self.pressure_type = pressure_type
        if product_series is not None:
            self.product_series = product_series
        if compensated_temperature_range_min is not None:
            self.compensated_temperature_range_min = compensated_temperature_range_min
        if compensated_temperature_range_max is not None:
            self.compensated_temperature_range_max = compensated_temperature_range_max
        if compensated_temperature_range_unit is not None:
            self.compensated_temperature_range_unit = compensated_temperature_range_unit
        if compensated_pressure_range_min is not None:
            self.compensated_pressure_range_min = compensated_pressure_range_min
        if compensated_pressure_range_max is not None:
            self.compensated_pressure_range_max = compensated_pressure_range_max
        if compensated_pressure_range_unit is not None:
            self.compensated_pressure_range_unit = compensated_pressure_range_unit
        if electric_supply_min is not None:
            self.electric_supply_min = electric_supply_min
        if electric_supply_max is not None:
            self.electric_supply_max = electric_supply_max
        if electric_supply_magnitude is not None:
            self.electric_supply_magnitude = electric_supply_magnitude
        if electric_supply_unit is not None:
            self.electric_supply_unit = electric_supply_unit
        if order_number is not None:
            self.order_number = order_number
        if order_position is not None:
            self.order_position = order_position
        if order_target_dispatch_date is not None:
            self.order_target_dispatch_date = order_target_dispatch_date
        if customer_order_number is not None:
            self.customer_order_number = customer_order_number
        if customer_reference_number is not None:
            self.customer_reference_number = customer_reference_number
        if customer_product_type is not None:
            self.customer_product_type = customer_product_type

    @property
    def id(self):
        """Gets the id of this MefistoViewModel.  # noqa: E501

        internal id  # noqa: E501

        :return: The id of this MefistoViewModel.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MefistoViewModel.

        internal id  # noqa: E501

        :param id: The id of this MefistoViewModel.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def customer_name(self):
        """Gets the customer_name of this MefistoViewModel.  # noqa: E501

        Customer name  # noqa: E501

        :return: The customer_name of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._customer_name

    @customer_name.setter
    def customer_name(self, customer_name):
        """Sets the customer_name of this MefistoViewModel.

        Customer name  # noqa: E501

        :param customer_name: The customer_name of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._customer_name = customer_name

    @property
    def customer_number(self):
        """Gets the customer_number of this MefistoViewModel.  # noqa: E501

        KELLER customer identification number  # noqa: E501

        :return: The customer_number of this MefistoViewModel.  # noqa: E501
        :rtype: int
        """
        return self._customer_number

    @customer_number.setter
    def customer_number(self, customer_number):
        """Sets the customer_number of this MefistoViewModel.

        KELLER customer identification number  # noqa: E501

        :param customer_number: The customer_number of this MefistoViewModel.  # noqa: E501
        :type: int
        """

        self._customer_number = customer_number

    @property
    def sub_customer_number(self):
        """Gets the sub_customer_number of this MefistoViewModel.  # noqa: E501

        KELLER customer identification number for a customer of a customer  # noqa: E501

        :return: The sub_customer_number of this MefistoViewModel.  # noqa: E501
        :rtype: int
        """
        return self._sub_customer_number

    @sub_customer_number.setter
    def sub_customer_number(self, sub_customer_number):
        """Sets the sub_customer_number of this MefistoViewModel.

        KELLER customer identification number for a customer of a customer  # noqa: E501

        :param sub_customer_number: The sub_customer_number of this MefistoViewModel.  # noqa: E501
        :type: int
        """

        self._sub_customer_number = sub_customer_number

    @property
    def remarks(self):
        """Gets the remarks of this MefistoViewModel.  # noqa: E501

        File creation date (UTC)  # noqa: E501

        :return: The remarks of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._remarks

    @remarks.setter
    def remarks(self, remarks):
        """Sets the remarks of this MefistoViewModel.

        File creation date (UTC)  # noqa: E501

        :param remarks: The remarks of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._remarks = remarks

    @property
    def serial_number(self):
        """Gets the serial_number of this MefistoViewModel.  # noqa: E501

        KELLER product serial number  # noqa: E501

        :return: The serial_number of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this MefistoViewModel.

        KELLER product serial number  # noqa: E501

        :param serial_number: The serial_number of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._serial_number = serial_number

    @property
    def product_number(self):
        """Gets the product_number of this MefistoViewModel.  # noqa: E501

        KELLER product number  # noqa: E501

        :return: The product_number of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._product_number

    @product_number.setter
    def product_number(self, product_number):
        """Sets the product_number of this MefistoViewModel.

        KELLER product number  # noqa: E501

        :param product_number: The product_number of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._product_number = product_number

    @property
    def product_type(self):
        """Gets the product_type of this MefistoViewModel.  # noqa: E501

        KELLER product type  # noqa: E501

        :return: The product_type of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._product_type

    @product_type.setter
    def product_type(self, product_type):
        """Sets the product_type of this MefistoViewModel.

        KELLER product type  # noqa: E501

        :param product_type: The product_type of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._product_type = product_type

    @property
    def pressure_type(self):
        """Gets the pressure_type of this MefistoViewModel.  # noqa: E501

        KELLER product pressure type  # noqa: E501

        :return: The pressure_type of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._pressure_type

    @pressure_type.setter
    def pressure_type(self, pressure_type):
        """Sets the pressure_type of this MefistoViewModel.

        KELLER product pressure type  # noqa: E501

        :param pressure_type: The pressure_type of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._pressure_type = pressure_type

    @property
    def product_series(self):
        """Gets the product_series of this MefistoViewModel.  # noqa: E501

        KELLER product series  # noqa: E501

        :return: The product_series of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._product_series

    @product_series.setter
    def product_series(self, product_series):
        """Sets the product_series of this MefistoViewModel.

        KELLER product series  # noqa: E501

        :param product_series: The product_series of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._product_series = product_series

    @property
    def compensated_temperature_range_min(self):
        """Gets the compensated_temperature_range_min of this MefistoViewModel.  # noqa: E501

        Temperature range over which the sensors characteristics have been compensated  Min  # noqa: E501

        :return: The compensated_temperature_range_min of this MefistoViewModel.  # noqa: E501
        :rtype: float
        """
        return self._compensated_temperature_range_min

    @compensated_temperature_range_min.setter
    def compensated_temperature_range_min(self, compensated_temperature_range_min):
        """Sets the compensated_temperature_range_min of this MefistoViewModel.

        Temperature range over which the sensors characteristics have been compensated  Min  # noqa: E501

        :param compensated_temperature_range_min: The compensated_temperature_range_min of this MefistoViewModel.  # noqa: E501
        :type: float
        """

        self._compensated_temperature_range_min = compensated_temperature_range_min

    @property
    def compensated_temperature_range_max(self):
        """Gets the compensated_temperature_range_max of this MefistoViewModel.  # noqa: E501

        Temperature range over which the sensors characteristics have been compensated  Max  # noqa: E501

        :return: The compensated_temperature_range_max of this MefistoViewModel.  # noqa: E501
        :rtype: float
        """
        return self._compensated_temperature_range_max

    @compensated_temperature_range_max.setter
    def compensated_temperature_range_max(self, compensated_temperature_range_max):
        """Sets the compensated_temperature_range_max of this MefistoViewModel.

        Temperature range over which the sensors characteristics have been compensated  Max  # noqa: E501

        :param compensated_temperature_range_max: The compensated_temperature_range_max of this MefistoViewModel.  # noqa: E501
        :type: float
        """

        self._compensated_temperature_range_max = compensated_temperature_range_max

    @property
    def compensated_temperature_range_unit(self):
        """Gets the compensated_temperature_range_unit of this MefistoViewModel.  # noqa: E501

        Temperature range over which the sensors characteristics have been compensated  Unit  # noqa: E501

        :return: The compensated_temperature_range_unit of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._compensated_temperature_range_unit

    @compensated_temperature_range_unit.setter
    def compensated_temperature_range_unit(self, compensated_temperature_range_unit):
        """Sets the compensated_temperature_range_unit of this MefistoViewModel.

        Temperature range over which the sensors characteristics have been compensated  Unit  # noqa: E501

        :param compensated_temperature_range_unit: The compensated_temperature_range_unit of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._compensated_temperature_range_unit = compensated_temperature_range_unit

    @property
    def compensated_pressure_range_min(self):
        """Gets the compensated_pressure_range_min of this MefistoViewModel.  # noqa: E501

        Pressure range over which the sensors characteristics have been compensated  Min  # noqa: E501

        :return: The compensated_pressure_range_min of this MefistoViewModel.  # noqa: E501
        :rtype: float
        """
        return self._compensated_pressure_range_min

    @compensated_pressure_range_min.setter
    def compensated_pressure_range_min(self, compensated_pressure_range_min):
        """Sets the compensated_pressure_range_min of this MefistoViewModel.

        Pressure range over which the sensors characteristics have been compensated  Min  # noqa: E501

        :param compensated_pressure_range_min: The compensated_pressure_range_min of this MefistoViewModel.  # noqa: E501
        :type: float
        """

        self._compensated_pressure_range_min = compensated_pressure_range_min

    @property
    def compensated_pressure_range_max(self):
        """Gets the compensated_pressure_range_max of this MefistoViewModel.  # noqa: E501

        Pressure range over which the sensors characteristics have been compensated  Max  # noqa: E501

        :return: The compensated_pressure_range_max of this MefistoViewModel.  # noqa: E501
        :rtype: float
        """
        return self._compensated_pressure_range_max

    @compensated_pressure_range_max.setter
    def compensated_pressure_range_max(self, compensated_pressure_range_max):
        """Sets the compensated_pressure_range_max of this MefistoViewModel.

        Pressure range over which the sensors characteristics have been compensated  Max  # noqa: E501

        :param compensated_pressure_range_max: The compensated_pressure_range_max of this MefistoViewModel.  # noqa: E501
        :type: float
        """

        self._compensated_pressure_range_max = compensated_pressure_range_max

    @property
    def compensated_pressure_range_unit(self):
        """Gets the compensated_pressure_range_unit of this MefistoViewModel.  # noqa: E501

        Pressure range over which the sensors characteristics have been compensated  Unit  # noqa: E501

        :return: The compensated_pressure_range_unit of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._compensated_pressure_range_unit

    @compensated_pressure_range_unit.setter
    def compensated_pressure_range_unit(self, compensated_pressure_range_unit):
        """Sets the compensated_pressure_range_unit of this MefistoViewModel.

        Pressure range over which the sensors characteristics have been compensated  Unit  # noqa: E501

        :param compensated_pressure_range_unit: The compensated_pressure_range_unit of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._compensated_pressure_range_unit = compensated_pressure_range_unit

    @property
    def electric_supply_min(self):
        """Gets the electric_supply_min of this MefistoViewModel.  # noqa: E501

        Nominal electric supply  Min  # noqa: E501

        :return: The electric_supply_min of this MefistoViewModel.  # noqa: E501
        :rtype: float
        """
        return self._electric_supply_min

    @electric_supply_min.setter
    def electric_supply_min(self, electric_supply_min):
        """Sets the electric_supply_min of this MefistoViewModel.

        Nominal electric supply  Min  # noqa: E501

        :param electric_supply_min: The electric_supply_min of this MefistoViewModel.  # noqa: E501
        :type: float
        """

        self._electric_supply_min = electric_supply_min

    @property
    def electric_supply_max(self):
        """Gets the electric_supply_max of this MefistoViewModel.  # noqa: E501

        Nominal electric supply  Max  # noqa: E501

        :return: The electric_supply_max of this MefistoViewModel.  # noqa: E501
        :rtype: float
        """
        return self._electric_supply_max

    @electric_supply_max.setter
    def electric_supply_max(self, electric_supply_max):
        """Sets the electric_supply_max of this MefistoViewModel.

        Nominal electric supply  Max  # noqa: E501

        :param electric_supply_max: The electric_supply_max of this MefistoViewModel.  # noqa: E501
        :type: float
        """

        self._electric_supply_max = electric_supply_max

    @property
    def electric_supply_magnitude(self):
        """Gets the electric_supply_magnitude of this MefistoViewModel.  # noqa: E501

        Nominal electric supply  Magnitude  # noqa: E501

        :return: The electric_supply_magnitude of this MefistoViewModel.  # noqa: E501
        :rtype: float
        """
        return self._electric_supply_magnitude

    @electric_supply_magnitude.setter
    def electric_supply_magnitude(self, electric_supply_magnitude):
        """Sets the electric_supply_magnitude of this MefistoViewModel.

        Nominal electric supply  Magnitude  # noqa: E501

        :param electric_supply_magnitude: The electric_supply_magnitude of this MefistoViewModel.  # noqa: E501
        :type: float
        """

        self._electric_supply_magnitude = electric_supply_magnitude

    @property
    def electric_supply_unit(self):
        """Gets the electric_supply_unit of this MefistoViewModel.  # noqa: E501

        Nominal electric supply  Unit  # noqa: E501

        :return: The electric_supply_unit of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._electric_supply_unit

    @electric_supply_unit.setter
    def electric_supply_unit(self, electric_supply_unit):
        """Sets the electric_supply_unit of this MefistoViewModel.

        Nominal electric supply  Unit  # noqa: E501

        :param electric_supply_unit: The electric_supply_unit of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._electric_supply_unit = electric_supply_unit

    @property
    def order_number(self):
        """Gets the order_number of this MefistoViewModel.  # noqa: E501

        KELLER purchase order number  # noqa: E501

        :return: The order_number of this MefistoViewModel.  # noqa: E501
        :rtype: int
        """
        return self._order_number

    @order_number.setter
    def order_number(self, order_number):
        """Sets the order_number of this MefistoViewModel.

        KELLER purchase order number  # noqa: E501

        :param order_number: The order_number of this MefistoViewModel.  # noqa: E501
        :type: int
        """

        self._order_number = order_number

    @property
    def order_position(self):
        """Gets the order_position of this MefistoViewModel.  # noqa: E501

        KELLER purchase order position  # noqa: E501

        :return: The order_position of this MefistoViewModel.  # noqa: E501
        :rtype: int
        """
        return self._order_position

    @order_position.setter
    def order_position(self, order_position):
        """Sets the order_position of this MefistoViewModel.

        KELLER purchase order position  # noqa: E501

        :param order_position: The order_position of this MefistoViewModel.  # noqa: E501
        :type: int
        """

        self._order_position = order_position

    @property
    def order_target_dispatch_date(self):
        """Gets the order_target_dispatch_date of this MefistoViewModel.  # noqa: E501

        Targeted dispatch date of the order  # noqa: E501

        :return: The order_target_dispatch_date of this MefistoViewModel.  # noqa: E501
        :rtype: datetime
        """
        return self._order_target_dispatch_date

    @order_target_dispatch_date.setter
    def order_target_dispatch_date(self, order_target_dispatch_date):
        """Sets the order_target_dispatch_date of this MefistoViewModel.

        Targeted dispatch date of the order  # noqa: E501

        :param order_target_dispatch_date: The order_target_dispatch_date of this MefistoViewModel.  # noqa: E501
        :type: datetime
        """

        self._order_target_dispatch_date = order_target_dispatch_date

    @property
    def customer_order_number(self):
        """Gets the customer_order_number of this MefistoViewModel.  # noqa: E501

        Customer internal purchase order number  # noqa: E501

        :return: The customer_order_number of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._customer_order_number

    @customer_order_number.setter
    def customer_order_number(self, customer_order_number):
        """Sets the customer_order_number of this MefistoViewModel.

        Customer internal purchase order number  # noqa: E501

        :param customer_order_number: The customer_order_number of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._customer_order_number = customer_order_number

    @property
    def customer_reference_number(self):
        """Gets the customer_reference_number of this MefistoViewModel.  # noqa: E501

        Customer internal reference number  # noqa: E501

        :return: The customer_reference_number of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._customer_reference_number

    @customer_reference_number.setter
    def customer_reference_number(self, customer_reference_number):
        """Sets the customer_reference_number of this MefistoViewModel.

        Customer internal reference number  # noqa: E501

        :param customer_reference_number: The customer_reference_number of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._customer_reference_number = customer_reference_number

    @property
    def customer_product_type(self):
        """Gets the customer_product_type of this MefistoViewModel.  # noqa: E501

        Customer internal product type  # noqa: E501

        :return: The customer_product_type of this MefistoViewModel.  # noqa: E501
        :rtype: str
        """
        return self._customer_product_type

    @customer_product_type.setter
    def customer_product_type(self, customer_product_type):
        """Sets the customer_product_type of this MefistoViewModel.

        Customer internal product type  # noqa: E501

        :param customer_product_type: The customer_product_type of this MefistoViewModel.  # noqa: E501
        :type: str
        """

        self._customer_product_type = customer_product_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MefistoViewModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MefistoViewModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
